ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignored-services: '*'
  strip-prefix: false
  sensitive-headers:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-service:
      path: /uaa/**
      url: http://localhost:5000/uaa/

    account-service:
      path: /accounts/**
      serviceId: account-service

#    statistics-service:
#      path: /statistics/**
#      serviceId: statistics-service

#    notification-service:
#      path: /notifications/**
#      serviceId: notification-service

server:
  port: 4000

spring:
  resources:
    static-locations: file:/Users/itachi/Desktop/spring-cloud-financial/front-end/resources/