ACCOUNT_SERVICE_PASSWORD: admin123
STATISTICS_SERVICE_PASSWORD: admin123
NOTIFICATION_SERVICE_PASSWORD: admin123

MONGODB_PASSWORD: user123

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:4444/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:4000/uaa/users/current